// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AppointmentCreate
 *
 * `POST /appointments`. The server computes `ends_at` from the type (R2).
 */
export type AppointmentCreate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Practitioner Id
     */
    practitioner_id: string;
    /**
     * Type
     */
    type: 'NURSE_TRIAGE' | 'INITIAL_CONSULT' | 'FOLLOW_UP';
    /**
     * Starts At
     */
    starts_at: string;
};

/**
 * AppointmentRead
 */
export type AppointmentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Patient Name
     */
    patient_name: string;
    /**
     * Practitioner Id
     */
    practitioner_id: string;
    /**
     * Type
     */
    type: 'NURSE_TRIAGE' | 'INITIAL_CONSULT' | 'FOLLOW_UP';
    /**
     * Status
     */
    status: 'BOOKED' | 'CONFIRMED' | 'ARRIVED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Ends At
     */
    ends_at: string;
    /**
     * Source
     */
    source: 'STAFF' | 'PUBLIC_BOOKING';
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AppointmentStatusUpdate
 *
 * `POST /appointments/{id}/status`.
 */
export type AppointmentStatusUpdate = {
    /**
     * Status
     */
    status: 'BOOKED' | 'CONFIRMED' | 'ARRIVED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';
};

/**
 * AuditEventRead
 *
 * One audit event as the API returns it — the design's envelope, and nothing else.
 *
 * `tenant_id` is not declared: the caller already knows its own tenant, and the row was read under
 * it. `prev_hash` and `hash` are exposed because verifying the trail is the point of reading it.
 */
export type AuditEventRead = {
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Actor Id
     */
    actor_id?: string | null;
    /**
     * Actor Role
     */
    actor_role?: string | null;
    /**
     * Action
     */
    action: string;
    /**
     * Resource Type
     */
    resource_type: string;
    /**
     * Resource Id
     */
    resource_id?: string | null;
    /**
     * Result
     */
    result: string;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Source Ip
     */
    source_ip?: string | null;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Correlation Id
     */
    correlation_id?: string | null;
    /**
     * Prev Hash
     */
    prev_hash: string;
    /**
     * Hash
     */
    hash: string;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    } | null;
};

/**
 * AuditEventsPublic
 *
 * A keyset page of audit events.
 *
 * `next_cursor` is opaque and `None` on the last page. `count` is the number of rows in this page,
 * not the tenant's total: the total is not disclosed and is not knowable without a scan, which R12
 * refuses.
 */
export type AuditEventsPublic = {
    /**
     * Data
     */
    data: Array<AuditEventRead>;
    /**
     * Count
     */
    count: number;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ClinicalRecordAppend
 *
 * The body of `PATCH /api/v1/clinical-records/{id}` and of `POST .../amendments`.
 *
 * Both routes append: the design says they are *"the same code path"*, so they share this schema.
 * A version is a complete document, not a patch to be merged, so the narrative is required in
 * full — an append that omitted it would have to copy the previous narrative forward, which would
 * silently attribute old text to a new author and time.
 *
 * `amendment_reason` is the design's API field for the `reason` column. Requirement R7 makes it
 * mandatory whenever the new version number is above 1; that check needs the record's current
 * version, so it runs in the service with the record loaded, and answers
 * `422 AMENDMENT_REASON_REQUIRED`.
 */
export type ClinicalRecordAppend = {
    /**
     * Body
     */
    body?: string | null;
    /**
     * Body Format
     */
    body_format?: string | null;
    soap?: SoapNote | null;
    /**
     * Amendment Reason
     */
    amendment_reason?: string | null;
};

/**
 * ClinicalRecordCreate
 *
 * The body of `POST /api/v1/clinical-records` (R1, R2).
 *
 * There is no `tenant_id`, `author_id`, `signed_at`, `version` or `current_version` field and
 * there never will be: `extra="forbid"` turns one into a `422` (R2).
 */
export type ClinicalRecordCreate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Record Type
     */
    record_type?: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Body Format
     */
    body_format?: string | null;
    soap?: SoapNote | null;
};

/**
 * ClinicalRecordDetail
 *
 * A record plus every version, ascending (R9). The shape `GET .../{id}` returns.
 */
export type ClinicalRecordDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Record Type
     */
    record_type: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Current Version
     */
    current_version: number;
    /**
     * Signed At
     */
    signed_at?: string | null;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Versions
     */
    versions: Array<ClinicalRecordVersionRead>;
};

/**
 * ClinicalRecordSummary
 *
 * One timeline entry: the record's metadata and its current version's narrative.
 */
export type ClinicalRecordSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Record Type
     */
    record_type: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Current Version
     */
    current_version: number;
    /**
     * Signed At
     */
    signed_at?: string | null;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    latest_version: ClinicalRecordVersionRead;
};

/**
 * ClinicalRecordVersionRead
 *
 * One version as the API returns it.
 *
 * No `tenant_id` is declared: the caller already knows its own tenant, and nothing that is not
 * needed is exposed. `body` is `HIGHLY_SENSITIVE` and this model is the **only** place it is
 * serialised — never into a log line, an error envelope or an audit payload (INV-5, R15).
 */
export type ClinicalRecordVersionRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Clinical Record Id
     */
    clinical_record_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Body
     */
    body: string;
    /**
     * Body Format
     */
    body_format: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Signed At
     */
    signed_at?: string | null;
    /**
     * Supersedes Version
     */
    supersedes_version?: number | null;
    /**
     * Amendment Reason
     */
    amendment_reason?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ClinicalRecordsPublic
 *
 * A keyset page of the patient timeline plus the cursor for the next page.
 */
export type ClinicalRecordsPublic = {
    /**
     * Data
     */
    data: Array<ClinicalRecordSummary>;
    /**
     * Count
     */
    count: number;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * DayAppointment
 *
 * One booking on a day's schedule, with the practitioner's display name (Today, R2).
 */
export type DayAppointment = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Patient Name
     */
    patient_name: string;
    /**
     * Practitioner Id
     */
    practitioner_id: string;
    /**
     * Type
     */
    type: 'NURSE_TRIAGE' | 'INITIAL_CONSULT' | 'FOLLOW_UP';
    /**
     * Status
     */
    status: 'BOOKED' | 'CONFIRMED' | 'ARRIVED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Ends At
     */
    ends_at: string;
    /**
     * Source
     */
    source: 'STAFF' | 'PUBLIC_BOOKING';
    /**
     * Created At
     */
    created_at: string;
    /**
     * Practitioner Name
     */
    practitioner_name: string | null;
};

/**
 * DaySchedule
 *
 * One clinic day's bookings, earliest first, and how many are in each status.
 *
 * `by_status` carries every status, zero included, so a client never has to know the vocabulary
 * to draw a count.
 */
export type DaySchedule = {
    /**
     * By Status
     */
    by_status: {
        [key: string]: number;
    };
    /**
     * Data
     */
    data: Array<DayAppointment>;
};

/**
 * DispatchRead
 *
 * The latest outbox row for a prescription - what the clinic may be told about delivery.
 *
 * `transport_configured` is the honest half of the answer: while it is `false`, a `QUEUED` row
 * has been accepted by ClinicOS and **has not been sent to any pharmacy**.
 */
export type DispatchRead = {
    /**
     * State
     */
    state: string;
    /**
     * Attempt Seq
     */
    attempt_seq: number;
    /**
     * Provider
     */
    provider: string | null;
    /**
     * Provider Reference
     */
    provider_reference: string | null;
    /**
     * Outcome Class
     */
    outcome_class: string | null;
    /**
     * Requested At
     */
    requested_at: string;
    /**
     * Resolved At
     */
    resolved_at: string | null;
    /**
     * Transport Configured
     */
    transport_configured: boolean;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InvitationAccept
 *
 * The body of `POST /api/v1/users/invitations/accept`: the emailed token and a new password.
 *
 * The password bounds are the API's own (`UserRegister`, `NewPassword`): 8 to 128 characters.
 */
export type InvitationAccept = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * InvitationAccepted
 *
 * The account the invitation belonged to, so the app can sign the person straight in.
 */
export type InvitationAccepted = {
    /**
     * Email
     */
    email: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OwnPermissionsRead
 *
 * The caller's own effective permission codes, sorted (`GET /api/v1/users/me/permissions`).
 *
 * Advisory UI data: the shell reads it to hide controls a role cannot use. It is the design's
 * self-permissions row (`03-design.md`, "Endpoints": *"advisory UI data only; never a
 * control"*). Every route still re-authorises
 * server-side (INV-3). No user or tenant identifier is echoed back: the caller is the session.
 */
export type OwnPermissionsRead = {
    /**
     * Permissions
     */
    permissions: Array<string>;
};

/**
 * PatientCreate
 *
 * The body of `POST /api/v1/patients`.
 *
 * There is no `tenant_id` field and there never will be: `extra="forbid"` turns one into
 * a `422` (INV-1). Identifier columns are absent for the same reason — their key custody
 * is an open item (`04-database-erd.md` open item 5), so no value is accepted yet.
 */
export type PatientCreate = {
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Preferred Name
     */
    preferred_name?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth: string;
    /**
     * Sex At Birth
     */
    sex_at_birth?: string | null;
    /**
     * Gender Identity
     */
    gender_identity?: string | null;
    /**
     * Address Line
     */
    address_line?: string | null;
    /**
     * Suburb
     */
    suburb?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postcode
     */
    postcode?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Deceased At
     */
    deceased_at?: string | null;
};

/**
 * PatientRead
 *
 * A patient as the API returns it.
 *
 * `from_attributes` lets the service hand over a declared model rather than a raw ORM
 * entity. No identifier column and no `tenant_id` is declared: the caller already knows
 * its own tenant, and nothing that is not needed is exposed.
 */
export type PatientRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Preferred Name
     */
    preferred_name?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth: string;
    /**
     * Sex At Birth
     */
    sex_at_birth?: string | null;
    /**
     * Gender Identity
     */
    gender_identity?: string | null;
    /**
     * Address Line
     */
    address_line?: string | null;
    /**
     * Suburb
     */
    suburb?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postcode
     */
    postcode?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Deceased At
     */
    deceased_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PatientSearch
 *
 * The body of `POST /api/v1/patients/search`.
 *
 * The term travels in the body, never in a URL (`01-requirements.md` R12), so it reaches no access
 * log, proxy log or browser history. It is never logged or audited either: the audit event records
 * which *kinds* of term were used (`query_filters`), not what they were (`02-user-stories.md` US-7).
 */
export type PatientSearch = {
    /**
     * Q
     */
    q: string;
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Limit
     */
    limit?: number;
};

/**
 * PatientUpdate
 *
 * The body of `PATCH /api/v1/patients/{patient_id}`.
 *
 * Every field is optional and applied with `exclude_unset`, so an omitted field is left
 * alone and an explicit `null` clears a nullable one. A `null` for a NOT NULL column is
 * rejected here rather than at the database.
 */
export type PatientUpdate = {
    /**
     * Given Name
     */
    given_name?: string | null;
    /**
     * Family Name
     */
    family_name?: string | null;
    /**
     * Preferred Name
     */
    preferred_name?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    /**
     * Sex At Birth
     */
    sex_at_birth?: string | null;
    /**
     * Gender Identity
     */
    gender_identity?: string | null;
    /**
     * Address Line
     */
    address_line?: string | null;
    /**
     * Suburb
     */
    suburb?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postcode
     */
    postcode?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Deceased At
     */
    deceased_at?: string | null;
};

/**
 * PatientsPublic
 *
 * One keyset page of patients, the total that matches, and the cursor for the next page.
 *
 * `count` is the number of live patients that match the request - the tenant's whole list for
 * `GET /patients`, the matches for a search - not the length of this page. `next_cursor` is `null`
 * on the last page. The cursor is opaque: it names the last row of this page by its internal id,
 * never by a name, so it carries nothing a URL or a log line must not hold.
 */
export type PatientsPublic = {
    /**
     * Data
     */
    data: Array<PatientRead>;
    /**
     * Count
     */
    count: number;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * PermissionRead
 *
 * One entry of the global permission catalogue.
 *
 * `permissions.id` is not exposed: `code` is the catalogue's stable identity and the join key is
 * internal. `permissions` is global read-only reference data (R7).
 */
export type PermissionRead = {
    /**
     * Code
     */
    code: string;
    /**
     * Description
     */
    description: string;
};

/**
 * PermissionsPublic
 *
 * The permission catalogue, or a computed subset of it, plus its size.
 */
export type PermissionsPublic = {
    /**
     * Data
     */
    data: Array<PermissionRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * PractitionerRead
 *
 * A bookable member of staff: an active account holding a Doctor, Authorised Prescriber or
 * Nurse role in the session's organisation.
 */
export type PractitionerRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: 'DOCTOR' | 'NURSE';
    /**
     * Title
     */
    title: string;
};

/**
 * PrescriberRead
 *
 * An account that may sign: the reviewing-doctor choice when staging.
 */
export type PrescriberRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * PrescribersPublic
 */
export type PrescribersPublic = {
    /**
     * Data
     */
    data: Array<PrescriberRead>;
};

/**
 * PrescriptionCreate
 *
 * `POST /api/v1/prescriptions`: stage a draft (FEAT-11 R1; docs2 07 R1).
 */
export type PrescriptionCreate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Prescriber Id
     */
    prescriber_id: string;
    /**
     * Medicine Name
     */
    medicine_name: string;
    /**
     * Tga Category
     */
    tga_category: string;
    /**
     * Dosage Form
     */
    dosage_form: string;
    /**
     * Dose Instruction
     */
    dose_instruction: string;
    /**
     * Quantity
     */
    quantity: number | string;
    /**
     * Repeats
     */
    repeats: number;
    /**
     * Triage Outcome
     */
    triage_outcome: string;
    /**
     * Conventional Therapy
     */
    conventional_therapy: string;
    /**
     * Date Of Service
     */
    date_of_service: string;
};

/**
 * PrescriptionDispatch
 *
 * `POST /api/v1/prescriptions/{id}/dispatch`: the step-up proof. The intent key is a header.
 */
export type PrescriptionDispatch = {
    /**
     * Step Up Token
     */
    step_up_token: string;
};

/**
 * PrescriptionQueueSummary
 *
 * The script queue at a glance (the Today page, `docs2/sdlc/08-today`).
 *
 * `by_state` carries every state, zero included. `QUEUED` while `transport_configured` is `false`
 * means accepted by ClinicOS and **not sent** to any pharmacy.
 */
export type PrescriptionQueueSummary = {
    /**
     * By State
     */
    by_state: {
        [key: string]: number;
    };
    /**
     * Transport Configured
     */
    transport_configured: boolean;
    /**
     * Actionable
     */
    actionable: Array<PrescriptionRead>;
    /**
     * Gate Refused
     */
    gate_refused: number;
    /**
     * Gate Checked
     */
    gate_checked: number;
};

/**
 * PrescriptionRead
 *
 * One prescription with the names a clinical list shows and, when actionable, the live gate.
 */
export type PrescriptionRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Patient Name
     */
    patient_name: string | null;
    /**
     * Prescriber Id
     */
    prescriber_id: string;
    /**
     * Prescriber Name
     */
    prescriber_name: string | null;
    /**
     * Drafted By
     */
    drafted_by: string;
    /**
     * Drafted By Name
     */
    drafted_by_name: string | null;
    /**
     * Medicine Name
     */
    medicine_name: string;
    /**
     * Tga Category
     */
    tga_category: string;
    /**
     * Dosage Form
     */
    dosage_form: string;
    /**
     * Dose Instruction
     */
    dose_instruction: string;
    /**
     * Quantity
     */
    quantity: string;
    /**
     * Repeats
     */
    repeats: number;
    /**
     * Triage Outcome
     */
    triage_outcome: string;
    /**
     * Conventional Therapy
     */
    conventional_therapy: string;
    /**
     * Date Of Service
     */
    date_of_service: string;
    /**
     * State
     */
    state: string;
    /**
     * Approval Id
     */
    approval_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Signed At
     */
    signed_at: string | null;
    gate: TgaMatchResponse | null;
    dispatch: DispatchRead | null;
};

/**
 * PrescriptionSign
 *
 * `POST /api/v1/prescriptions/{id}/sign`: the single-use step-up proof, and nothing else.
 */
export type PrescriptionSign = {
    /**
     * Step Up Token
     */
    step_up_token: string;
};

/**
 * PrescriptionsPublic
 *
 * One keyset page of the queue and its history, newest first.
 */
export type PrescriptionsPublic = {
    /**
     * Data
     */
    data: Array<PrescriptionRead>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * PublicBookingCreated
 *
 * The confirmation. The same shape whether the patient was new or matched (never says which).
 */
export type PublicBookingCreated = {
    /**
     * Reference
     */
    reference: string;
};

/**
 * PublicBookingRequest
 *
 * `POST /public/{clinic_slug}/bookings`: a slot, who the patient is, and the APP 5 consent.
 */
export type PublicBookingRequest = {
    /**
     * Type
     */
    type: 'NURSE_TRIAGE' | 'INITIAL_CONSULT' | 'FOLLOW_UP';
    /**
     * Practitioner Id
     */
    practitioner_id: string;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Date Of Birth
     */
    date_of_birth: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Consent
     */
    consent: true;
};

/**
 * PublicSlot
 *
 * One free, bookable time. Only what the booking page shows: never another patient's data.
 */
export type PublicSlot = {
    /**
     * Practitioner Id
     */
    practitioner_id: string;
    /**
     * Practitioner Name
     */
    practitioner_name: string;
    /**
     * Starts At
     */
    starts_at: string;
    /**
     * Ends At
     */
    ends_at: string;
};

/**
 * RoleAssignmentCreate
 *
 * The body of `POST /api/v1/users/{user_id}/roles`.
 *
 * Only `role_id` is accepted. A `tenant_id` (INV-1), a `granted_by` or a `user_id` is an unknown
 * field and is rejected `422` before any query runs — the design's step 5 names exactly those three.
 */
export type RoleAssignmentCreate = {
    /**
     * Role Id
     */
    role_id: string;
};

/**
 * RoleRead
 *
 * A tenant-scoped role and the permission bundle it resolves to.
 */
export type RoleRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is System
     */
    is_system: boolean;
    /**
     * Permissions
     */
    permissions: Array<PermissionRead>;
};

/**
 * RolesPublic
 *
 * The organisation's roles, ordered by code, plus their count.
 */
export type RolesPublic = {
    /**
     * Data
     */
    data: Array<RoleRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * SoapNote
 *
 * The `subjective` / `objective` / `assessment` / `plan` authoring surface.
 *
 * This is a **serialisation** of the single narrative column, never a storage shape: the service
 * renders it into `clinical_record_versions.body` and no SOAP column exists anywhere (R3).
 */
export type SoapNote = {
    /**
     * Subjective
     */
    subjective?: string | null;
    /**
     * Objective
     */
    objective?: string | null;
    /**
     * Assessment
     */
    assessment?: string | null;
    /**
     * Plan
     */
    plan?: string | null;
};

/**
 * StaffInvite
 *
 * The body of `POST /api/v1/users/staff`: who to invite and the role(s) they start with.
 *
 * Strict (`extra="forbid"`) for every key but one. **A `tenant_id` is ignored and audited** rather
 * than refused (INV-1: *"a `tenant_id` from a body, header or query parameter is ignored and audited
 * as a cross-tenant attempt"*): the wrap validator drops it before validation and records that it
 * was there, and the service writes the audit event in the invitation's own transaction. The
 * invitation always lands in the session's tenant. There is no password field: the invitee
 * chooses their own through the emailed link.
 */
export type StaffInvite = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Role Ids
     */
    role_ids: Array<string>;
};

/**
 * StaffMemberRead
 *
 * One account of the caller's organisation (`GET`/`POST /api/v1/users/staff`).
 *
 * No `tenant_id` (the caller's own), no `is_superuser` (a platform attribute an organisation does
 * not administer) and no credential material.
 */
export type StaffMemberRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Roles
     */
    roles: Array<StaffRoleRead>;
};

/**
 * StaffPublic
 *
 * One page of the organisation's staff, plus the organisation's total.
 */
export type StaffPublic = {
    /**
     * Data
     */
    data: Array<StaffMemberRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * StaffRoleRead
 *
 * One role a staff member holds: enough to show and to address it, not its bundle.
 */
export type StaffRoleRead = {
    /**
     * Role Id
     */
    role_id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * StepUpGrantRead
 *
 * The single-use proof. `step_up_token` is SECRET: held by the client for one call, never logged.
 */
export type StepUpGrantRead = {
    /**
     * Step Up Token
     */
    step_up_token: string;
    /**
     * Operation
     */
    operation: string;
    /**
     * Resource Id
     */
    resource_id: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * StepUpRequest
 *
 * `POST /api/v1/auth/step-up`: re-prove the session's factor for one operation on one resource.
 *
 * The interim factor is the account password (ADR-F002; D-003 decides the real one). `operation`
 * is a closed vocabulary and `resource_id` is the record the operation will act on, so the grant
 * this returns cannot be spent on anything else. No `user_id` or `tenant_id`: both are the session.
 */
export type StepUpRequest = {
    /**
     * Password
     */
    password: string;
    /**
     * Operation
     */
    operation: 'prescription.sign' | 'prescription.dispatch';
    /**
     * Resource Id
     */
    resource_id: string;
};

/**
 * SupersedeChainLink
 *
 * One row of the reconstructible history: what replaced what, and when it stopped being live.
 */
export type SupersedeChainLink = {
    /**
     * Id
     */
    id: string;
    /**
     * State
     */
    state: string;
    /**
     * Valid From
     */
    valid_from: string;
    /**
     * Valid To
     */
    valid_to: string;
    /**
     * Supersedes Id
     */
    supersedes_id: string | null;
    /**
     * Superseded By Id
     */
    superseded_by_id: string | null;
};

/**
 * TenantCurrentRead
 *
 * The caller's own tenant, as `GET /api/v1/tenants/current` returns it.
 *
 * `status` and `data_region` are shown (US-1). `retention_profile` and `legal_name` are not: the
 * application role holds no `SELECT` on either (`03-design.md`, "Database privileges").
 */
export type TenantCurrentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Status
     */
    status: string;
    /**
     * Data Region
     */
    data_region: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TenantSettingsUpdate
 *
 * The body of `PATCH /api/v1/tenants/current` — no field is settable yet.
 *
 * `extra="forbid"` is what makes that a control rather than a comment: a client cannot smuggle a
 * `tenant_id` (or any future setting) past the route, and any name it sends is a `422` decided by the
 * validation layer, in the same order the design fixes (validate against a strict schema).
 */
export type TenantSettingsUpdate = {
    [key: string]: never;
};

/**
 * TgaApprovalCreate
 *
 * `POST /api/v1/tga-approvals` — a manual entry, which starts `PENDING` (R1, R5, US-1).
 *
 * There is no `state`, no `source`, no `created_by`, no `verified_by` and no `tenant_id`: every one
 * of those is the server's, and a body that carries one is refused as an unknown field.
 */
export type TgaApprovalCreate = {
    /**
     * Valid From
     */
    valid_from: string;
    /**
     * Valid To
     */
    valid_to: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Tga Category
     */
    tga_category: string;
    /**
     * Dosage Form
     */
    dosage_form: string;
    /**
     * Approval Reference
     */
    approval_reference: string;
    /**
     * Creation Reason
     */
    creation_reason: string;
};

/**
 * TgaApprovalDetail
 *
 * The detail read: the approval plus its supersede chain (T2-12).
 */
export type TgaApprovalDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Tga Category
     */
    tga_category: string;
    /**
     * Dosage Form
     */
    dosage_form: string;
    /**
     * Approval Reference
     */
    approval_reference: string;
    /**
     * Valid From
     */
    valid_from: string;
    /**
     * Valid To
     */
    valid_to: string;
    /**
     * State
     */
    state: string;
    /**
     * Source
     */
    source: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Verified By
     */
    verified_by: string | null;
    /**
     * Verified At
     */
    verified_at: string | null;
    /**
     * Revoked By
     */
    revoked_by: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
    /**
     * Revoked Reason Code
     */
    revoked_reason_code: string | null;
    /**
     * Superseded By Id
     */
    superseded_by_id: string | null;
    /**
     * Supersedes Id
     */
    supersedes_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Supersede Chain
     */
    supersede_chain?: Array<SupersedeChainLink>;
};

/**
 * TgaApprovalDigest
 *
 * The approvals needing action, at a glance (the Today page, `docs2/sdlc/08-today`).
 *
 * The register's "Needs action" set, split in two: approvals waiting for their four-eyes check,
 * and `ACTIVE` approvals whose last covered day falls within `expiring_within_days` of today
 * (Australia/Sydney), already-lapsed ones the expiry job has not reached included. The two counts
 * are the practice's totals; the two lists are bounded.
 */
export type TgaApprovalDigest = {
    /**
     * Pending Verification
     */
    pending_verification: number;
    /**
     * Expiring
     */
    expiring: number;
    /**
     * Expiring Within Days
     */
    expiring_within_days: number;
    /**
     * Pending
     */
    pending: Array<TgaApprovalRegisterRow>;
    /**
     * Expiring Soon
     */
    expiring_soon: Array<TgaApprovalRegisterRow>;
};

/**
 * TgaApprovalRead
 *
 * One approval. No `validity_interval` column, no internals, no document store key.
 */
export type TgaApprovalRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Tga Category
     */
    tga_category: string;
    /**
     * Dosage Form
     */
    dosage_form: string;
    /**
     * Approval Reference
     */
    approval_reference: string;
    /**
     * Valid From
     */
    valid_from: string;
    /**
     * Valid To
     */
    valid_to: string;
    /**
     * State
     */
    state: string;
    /**
     * Source
     */
    source: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Verified By
     */
    verified_by: string | null;
    /**
     * Verified At
     */
    verified_at: string | null;
    /**
     * Revoked By
     */
    revoked_by: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
    /**
     * Revoked Reason Code
     */
    revoked_reason_code: string | null;
    /**
     * Superseded By Id
     */
    superseded_by_id: string | null;
    /**
     * Supersedes Id
     */
    supersedes_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TgaApprovalRegister
 *
 * One keyset page of the practice-wide register, plus the practice's totals.
 */
export type TgaApprovalRegister = {
    /**
     * Data
     */
    data: Array<TgaApprovalRegisterRow>;
    /**
     * Count
     */
    count: number;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
    counts: TgaApprovalRegisterCounts;
};

/**
 * TgaApprovalRegisterCounts
 *
 * The practice's totals, independent of the page and of the filter the caller asked for.
 *
 * The register's filter chips show a count each (`docs2/sdlc/05-approvals/requirements.md` R7),
 * and those counts cannot be derived from one page of one filter.
 */
export type TgaApprovalRegisterCounts = {
    /**
     * By State
     */
    by_state: {
        [key: string]: number;
    };
    /**
     * Expiring
     */
    expiring: number;
    /**
     * Expiring Within Days
     */
    expiring_within_days: number;
};

/**
 * TgaApprovalRegisterRow
 *
 * One register row: the approval and the name of the patient it belongs to.
 *
 * `patient_display_name` is `None` when the patient is no longer readable (soft-deleted), so the
 * row is still listed rather than silently dropped from a regulatory register.
 */
export type TgaApprovalRegisterRow = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Tga Category
     */
    tga_category: string;
    /**
     * Dosage Form
     */
    dosage_form: string;
    /**
     * Approval Reference
     */
    approval_reference: string;
    /**
     * Valid From
     */
    valid_from: string;
    /**
     * Valid To
     */
    valid_to: string;
    /**
     * State
     */
    state: string;
    /**
     * Source
     */
    source: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Verified By
     */
    verified_by: string | null;
    /**
     * Verified At
     */
    verified_at: string | null;
    /**
     * Revoked By
     */
    revoked_by: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
    /**
     * Revoked Reason Code
     */
    revoked_reason_code: string | null;
    /**
     * Superseded By Id
     */
    superseded_by_id: string | null;
    /**
     * Supersedes Id
     */
    supersedes_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Patient Display Name
     */
    patient_display_name: string | null;
};

/**
 * TgaApprovalRevoke
 *
 * `POST /api/v1/tga-approvals/{id}/revoke` — a mandatory reason **code** (R9, T2-14).
 *
 * A code, not free text: `03-design.md` fixes that for `revoked_reason_code`, and free text in a
 * revocation reason is clinical narrative that would reach the audit trail and the logs.
 */
export type TgaApprovalRevoke = {
    /**
     * Reason Code
     */
    reason_code: string;
};

/**
 * TgaApprovalSupersede
 *
 * `POST /api/v1/tga-approvals/{id}/supersede` — the replacement grant (T2-9, design §2).
 *
 * The replacement is created `PENDING` like any other manual entry: extensions and dosage changes
 * require a new grant record, and a new grant record requires independent verification (R5, R12).
 * What makes it a *supersede* is that `supersedes_id` names the grant it replaces, and the
 * predecessor moves to `SUPERSEDED` — atomically, in the transaction that activates the
 * replacement — rather than being edited in place.
 */
export type TgaApprovalSupersede = {
    /**
     * Valid From
     */
    valid_from: string;
    /**
     * Valid To
     */
    valid_to: string;
    /**
     * Approval Reference
     */
    approval_reference: string;
    /**
     * Creation Reason
     */
    creation_reason: string;
};

/**
 * TgaApprovalVerify
 *
 * `POST /api/v1/tga-approvals/{id}/verify` — step 2 of four-eyes (R5, T2-13).
 *
 * The verifier must re-enter the application number from the source document: a verification that
 * does not carry the reference it is verifying is not a check of anything, and the service refuses
 * a mismatch. The actor is never in the body — it is the authenticated session.
 */
export type TgaApprovalVerify = {
    /**
     * Tga Application Number
     */
    tga_application_number: string;
};

/**
 * TgaApprovalsPublic
 *
 * One keyset page of approvals.
 */
export type TgaApprovalsPublic = {
    /**
     * Data
     */
    data: Array<TgaApprovalRead>;
    /**
     * Count
     */
    count: number;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * TgaMatchRequest
 *
 * `POST /api/v1/tga-approvals/match` — the point-in-time gate lookup (T2-27, T2-29).
 *
 * `POST` and not `GET`, deliberately: `patient_id`, the category, the dosage form and the service
 * date are all PHI-adjacent, and a query string is written to access logs, proxy logs and browser
 * history. `date_of_service` is the consultation date the decision is evaluated at — never "now",
 * which is what makes a late expiry sweep unable to allow an expired approval (design, "Expiry
 * handling").
 */
export type TgaMatchRequest = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Tga Category
     */
    tga_category: string;
    /**
     * Dosage Form
     */
    dosage_form: string;
    /**
     * Date Of Service
     */
    date_of_service: string;
};

/**
 * TgaMatchResponse
 *
 * The gate's answer (T2-27).
 *
 * `matched = false` is a `200`, not an error: a non-match is the safety gate working, and the
 * reason code is what the prescribing screen explains. `state` and `approval_id` are populated even
 * on a refusal when a row at the grain exists, so the clinician can be told *why*.
 */
export type TgaMatchResponse = {
    /**
     * Matched
     */
    matched: boolean;
    /**
     * Reason Code
     */
    reason_code: string | null;
    /**
     * State
     */
    state: string | null;
    /**
     * Approval Id
     */
    approval_id: string | null;
    validity_interval: ValidityInterval | null;
    /**
     * Date Of Service
     */
    date_of_service: string;
    /**
     * Evaluated Timezone
     */
    evaluated_timezone: string;
};

/**
 * TodaySummary
 *
 * `GET /api/v1/dashboard/today`: the clinic's day in one read.
 */
export type TodaySummary = {
    /**
     * Date
     */
    date: string;
    /**
     * Timezone
     */
    timezone: string;
    appointments: DaySchedule | null;
    scripts: PrescriptionQueueSummary | null;
    approvals: TgaApprovalDigest | null;
    /**
     * Withheld
     */
    withheld: Array<'appointments' | 'scripts' | 'approvals'>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPermissionsRead
 *
 * The effective permission set of one account, computed server-side from its roles.
 *
 * The design names this "effective set, computed server-side": nothing here comes from the request,
 * and the set is the union of the account's role bundles (R1).
 */
export type UserPermissionsRead = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Permissions
     */
    permissions: Array<PermissionRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Tenant Id
     */
    tenant_id?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Clinic Name
     */
    clinic_name?: string | null;
};

/**
 * UserRoleRead
 *
 * One role an account holds inside the caller's tenant.
 *
 * `granted_at` is returned because an access review needs the age of the grant (US-2); the granter's
 * identifier is not.
 */
export type UserRoleRead = {
    /**
     * Role Id
     */
    role_id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is System
     */
    is_system: boolean;
    /**
     * Granted At
     */
    granted_at: string;
};

/**
 * UserRolesPublic
 *
 * The roles one account holds, plus their count.
 */
export type UserRolesPublic = {
    /**
     * Data
     */
    data: Array<UserRoleRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ValidityInterval
 *
 * The window a match was decided against, with the boundary rule it was read under.
 */
export type ValidityInterval = {
    /**
     * Valid From
     */
    valid_from: string;
    /**
     * Valid To
     */
    valid_to: string;
    /**
     * Bounds
     */
    bounds?: '[)';
};

export type healthReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready/';
};

export type healthReadinessErrors = {
    /**
     * The process cannot reach its database.
     */
    503: boolean;
};

export type healthReadinessError = healthReadinessErrors[keyof healthReadinessErrors];

export type healthReadinessResponses = {
    /**
     * The process can serve requests.
     */
    200: boolean;
};

export type healthReadinessResponse = healthReadinessResponses[keyof healthReadinessResponses];

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type usersListStaffData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/staff';
};

export type usersListStaffErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersListStaffError = usersListStaffErrors[keyof usersListStaffErrors];

export type usersListStaffResponses = {
    /**
     * Successful Response
     */
    200: StaffPublic;
};

export type usersListStaffResponse = usersListStaffResponses[keyof usersListStaffResponses];

export type usersInviteStaffData = {
    body: StaffInvite;
    path?: never;
    query?: never;
    url: '/api/v1/users/staff';
};

export type usersInviteStaffErrors = {
    /**
     * A role is absent, or belongs to another organisation
     */
    404: unknown;
    /**
     * Refused: the address already has an account. The same answer whichever organisation holds it, so no organisation is disclosed.
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
    /**
     * Outgoing mail is not configured, so no invitation can be sent
     */
    503: unknown;
};

export type usersInviteStaffError = usersInviteStaffErrors[keyof usersInviteStaffErrors];

export type usersInviteStaffResponses = {
    /**
     * Successful Response
     */
    201: StaffMemberRead;
};

export type usersInviteStaffResponse = usersInviteStaffResponses[keyof usersInviteStaffResponses];

export type usersAcceptInvitationData = {
    body: InvitationAccept;
    path?: never;
    query?: never;
    url: '/api/v1/users/invitations/accept';
};

export type usersAcceptInvitationErrors = {
    /**
     * The link is invalid, expired or already used
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersAcceptInvitationError = usersAcceptInvitationErrors[keyof usersAcceptInvitationErrors];

export type usersAcceptInvitationResponses = {
    /**
     * Successful Response
     */
    200: InvitationAccepted;
};

export type usersAcceptInvitationResponse = usersAcceptInvitationResponses[keyof usersAcceptInvitationResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type patientsListPatientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/patients';
};

export type patientsListPatientsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsListPatientsError = patientsListPatientsErrors[keyof patientsListPatientsErrors];

export type patientsListPatientsResponses = {
    /**
     * Successful Response
     */
    200: PatientsPublic;
};

export type patientsListPatientsResponse = patientsListPatientsResponses[keyof patientsListPatientsResponses];

export type patientsCreatePatientData = {
    body: PatientCreate;
    path?: never;
    query?: never;
    url: '/api/v1/patients';
};

export type patientsCreatePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsCreatePatientError = patientsCreatePatientErrors[keyof patientsCreatePatientErrors];

export type patientsCreatePatientResponses = {
    /**
     * Successful Response
     */
    201: PatientRead;
};

export type patientsCreatePatientResponse = patientsCreatePatientResponses[keyof patientsCreatePatientResponses];

export type patientsSearchPatientsData = {
    body: PatientSearch;
    path?: never;
    query?: never;
    url: '/api/v1/patients/search';
};

export type patientsSearchPatientsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsSearchPatientsError = patientsSearchPatientsErrors[keyof patientsSearchPatientsErrors];

export type patientsSearchPatientsResponses = {
    /**
     * Successful Response
     */
    200: PatientsPublic;
};

export type patientsSearchPatientsResponse = patientsSearchPatientsResponses[keyof patientsSearchPatientsResponses];

export type patientsReadPatientData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}';
};

export type patientsReadPatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsReadPatientError = patientsReadPatientErrors[keyof patientsReadPatientErrors];

export type patientsReadPatientResponses = {
    /**
     * Successful Response
     */
    200: PatientRead;
};

export type patientsReadPatientResponse = patientsReadPatientResponses[keyof patientsReadPatientResponses];

export type patientsUpdatePatientData = {
    body: PatientUpdate;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}';
};

export type patientsUpdatePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsUpdatePatientError = patientsUpdatePatientErrors[keyof patientsUpdatePatientErrors];

export type patientsUpdatePatientResponses = {
    /**
     * Successful Response
     */
    200: PatientRead;
};

export type patientsUpdatePatientResponse = patientsUpdatePatientResponses[keyof patientsUpdatePatientResponses];

export type rolesListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/roles';
};

export type rolesListRolesResponses = {
    /**
     * Successful Response
     */
    200: RolesPublic;
};

export type rolesListRolesResponse = rolesListRolesResponses[keyof rolesListRolesResponses];

export type permissionsListPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/permissions';
};

export type permissionsListPermissionsResponses = {
    /**
     * Successful Response
     */
    200: PermissionsPublic;
};

export type permissionsListPermissionsResponse = permissionsListPermissionsResponses[keyof permissionsListPermissionsResponses];

export type usersReadOwnPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/permissions';
};

export type usersReadOwnPermissionsResponses = {
    /**
     * Successful Response
     */
    200: OwnPermissionsRead;
};

export type usersReadOwnPermissionsResponse = usersReadOwnPermissionsResponses[keyof usersReadOwnPermissionsResponses];

export type usersReadUserRolesData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/roles';
};

export type usersReadUserRolesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserRolesError = usersReadUserRolesErrors[keyof usersReadUserRolesErrors];

export type usersReadUserRolesResponses = {
    /**
     * Successful Response
     */
    200: UserRolesPublic;
};

export type usersReadUserRolesResponse = usersReadUserRolesResponses[keyof usersReadUserRolesResponses];

export type usersAssignRoleData = {
    body: RoleAssignmentCreate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/roles';
};

export type usersAssignRoleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersAssignRoleError = usersAssignRoleErrors[keyof usersAssignRoleErrors];

export type usersAssignRoleResponses = {
    /**
     * The account already held the role; nothing was written
     */
    200: RoleRead;
    /**
     * Successful Response
     */
    201: RoleRead;
};

export type usersAssignRoleResponse = usersAssignRoleResponses[keyof usersAssignRoleResponses];

export type usersReadUserPermissionsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/permissions';
};

export type usersReadUserPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserPermissionsError = usersReadUserPermissionsErrors[keyof usersReadUserPermissionsErrors];

export type usersReadUserPermissionsResponses = {
    /**
     * Successful Response
     */
    200: UserPermissionsRead;
};

export type usersReadUserPermissionsResponse = usersReadUserPermissionsResponses[keyof usersReadUserPermissionsResponses];

export type usersRevokeRoleData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/roles/{role_id}';
};

export type usersRevokeRoleErrors = {
    /**
     * Refused: this is the organisation's last role granting `users:manage` (R8). Assign another administrator first.
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRevokeRoleError = usersRevokeRoleErrors[keyof usersRevokeRoleErrors];

export type usersRevokeRoleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersRevokeRoleResponse = usersRevokeRoleResponses[keyof usersRevokeRoleResponses];

export type tenantsReadCurrentTenantData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tenants/current';
};

export type tenantsReadCurrentTenantResponses = {
    /**
     * Successful Response
     */
    200: TenantCurrentRead;
};

export type tenantsReadCurrentTenantResponse = tenantsReadCurrentTenantResponses[keyof tenantsReadCurrentTenantResponses];

export type tenantsUpdateCurrentTenantData = {
    body: TenantSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/tenants/current';
};

export type tenantsUpdateCurrentTenantErrors = {
    /**
     * Refused. `PERMISSION_NOT_HELD` when the caller does not hold `tenant:configure`; `STEP_UP_REQUIRED` for a caller who does, because the step-up control this route requires is not built (feature 02, blocked by D-003). Nothing is written.
     */
    403: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsUpdateCurrentTenantError = tenantsUpdateCurrentTenantErrors[keyof tenantsUpdateCurrentTenantErrors];

export type tenantsUpdateCurrentTenantResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type auditListAuditEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Action
         */
        action?: string | null;
        /**
         * Actor Id
         */
        actor_id?: string | null;
        /**
         * Resource Type
         */
        resource_type?: string | null;
        /**
         * Resource Id
         */
        resource_id?: string | null;
        /**
         * Result
         */
        result?: string | null;
        /**
         * From
         */
        from?: string | null;
        /**
         * To
         */
        to?: string | null;
    };
    url: '/api/v1/audit/events';
};

export type auditListAuditEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type auditListAuditEventsError = auditListAuditEventsErrors[keyof auditListAuditEventsErrors];

export type auditListAuditEventsResponses = {
    /**
     * Successful Response
     */
    200: AuditEventsPublic;
};

export type auditListAuditEventsResponse = auditListAuditEventsResponses[keyof auditListAuditEventsResponses];

export type auditReadAuditEventData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/api/v1/audit/events/{event_id}';
};

export type auditReadAuditEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type auditReadAuditEventError = auditReadAuditEventErrors[keyof auditReadAuditEventErrors];

export type auditReadAuditEventResponses = {
    /**
     * Successful Response
     */
    200: AuditEventRead;
};

export type auditReadAuditEventResponse = auditReadAuditEventResponses[keyof auditReadAuditEventResponses];

export type clinicalRecordsCreateClinicalRecordData = {
    body: ClinicalRecordCreate;
    path?: never;
    query?: never;
    url: '/api/v1/clinical-records';
};

export type clinicalRecordsCreateClinicalRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsCreateClinicalRecordError = clinicalRecordsCreateClinicalRecordErrors[keyof clinicalRecordsCreateClinicalRecordErrors];

export type clinicalRecordsCreateClinicalRecordResponses = {
    /**
     * Successful Response
     */
    201: ClinicalRecordDetail;
};

export type clinicalRecordsCreateClinicalRecordResponse = clinicalRecordsCreateClinicalRecordResponses[keyof clinicalRecordsCreateClinicalRecordResponses];

export type clinicalRecordsReadClinicalRecordData = {
    body?: never;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}';
};

export type clinicalRecordsReadClinicalRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsReadClinicalRecordError = clinicalRecordsReadClinicalRecordErrors[keyof clinicalRecordsReadClinicalRecordErrors];

export type clinicalRecordsReadClinicalRecordResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordDetail;
};

export type clinicalRecordsReadClinicalRecordResponse = clinicalRecordsReadClinicalRecordResponses[keyof clinicalRecordsReadClinicalRecordResponses];

export type clinicalRecordsAppendClinicalRecordVersionData = {
    body: ClinicalRecordAppend;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}';
};

export type clinicalRecordsAppendClinicalRecordVersionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsAppendClinicalRecordVersionError = clinicalRecordsAppendClinicalRecordVersionErrors[keyof clinicalRecordsAppendClinicalRecordVersionErrors];

export type clinicalRecordsAppendClinicalRecordVersionResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordDetail;
};

export type clinicalRecordsAppendClinicalRecordVersionResponse = clinicalRecordsAppendClinicalRecordVersionResponses[keyof clinicalRecordsAppendClinicalRecordVersionResponses];

export type clinicalRecordsReadClinicalRecordVersionData = {
    body?: never;
    path: {
        /**
         * Record Id
         */
        record_id: string;
        /**
         * Version
         */
        version: number;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}/versions/{version}';
};

export type clinicalRecordsReadClinicalRecordVersionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsReadClinicalRecordVersionError = clinicalRecordsReadClinicalRecordVersionErrors[keyof clinicalRecordsReadClinicalRecordVersionErrors];

export type clinicalRecordsReadClinicalRecordVersionResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordVersionRead;
};

export type clinicalRecordsReadClinicalRecordVersionResponse = clinicalRecordsReadClinicalRecordVersionResponses[keyof clinicalRecordsReadClinicalRecordVersionResponses];

export type clinicalRecordsListPatientClinicalRecordsData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/patients/{patient_id}/clinical-records';
};

export type clinicalRecordsListPatientClinicalRecordsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsListPatientClinicalRecordsError = clinicalRecordsListPatientClinicalRecordsErrors[keyof clinicalRecordsListPatientClinicalRecordsErrors];

export type clinicalRecordsListPatientClinicalRecordsResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordsPublic;
};

export type clinicalRecordsListPatientClinicalRecordsResponse = clinicalRecordsListPatientClinicalRecordsResponses[keyof clinicalRecordsListPatientClinicalRecordsResponses];

export type clinicalRecordsAmendClinicalRecordData = {
    body: ClinicalRecordAppend;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}/amendments';
};

export type clinicalRecordsAmendClinicalRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsAmendClinicalRecordError = clinicalRecordsAmendClinicalRecordErrors[keyof clinicalRecordsAmendClinicalRecordErrors];

export type clinicalRecordsAmendClinicalRecordResponses = {
    /**
     * Successful Response
     */
    201: ClinicalRecordDetail;
};

export type clinicalRecordsAmendClinicalRecordResponse = clinicalRecordsAmendClinicalRecordResponses[keyof clinicalRecordsAmendClinicalRecordResponses];

export type clinicalRecordsSignClinicalRecordData = {
    body?: never;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}/sign';
};

export type clinicalRecordsSignClinicalRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsSignClinicalRecordError = clinicalRecordsSignClinicalRecordErrors[keyof clinicalRecordsSignClinicalRecordErrors];

export type clinicalRecordsSignClinicalRecordResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordDetail;
};

export type clinicalRecordsSignClinicalRecordResponse = clinicalRecordsSignClinicalRecordResponses[keyof clinicalRecordsSignClinicalRecordResponses];

export type tgaApprovalsListTgaApprovalsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * State
         */
        state?: Array<'PENDING' | 'ACTIVE' | 'EXPIRED' | 'REJECTED' | 'REVOKED' | 'SUPERSEDED'> | null;
        /**
         * Expiring Within Days
         */
        expiring_within_days?: number | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/tga-approvals';
};

export type tgaApprovalsListTgaApprovalsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tgaApprovalsListTgaApprovalsError = tgaApprovalsListTgaApprovalsErrors[keyof tgaApprovalsListTgaApprovalsErrors];

export type tgaApprovalsListTgaApprovalsResponses = {
    /**
     * Successful Response
     */
    200: TgaApprovalRegister;
};

export type tgaApprovalsListTgaApprovalsResponse = tgaApprovalsListTgaApprovalsResponses[keyof tgaApprovalsListTgaApprovalsResponses];

export type tgaApprovalsCreateTgaApprovalData = {
    body: TgaApprovalCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tga-approvals';
};

export type tgaApprovalsCreateTgaApprovalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tgaApprovalsCreateTgaApprovalError = tgaApprovalsCreateTgaApprovalErrors[keyof tgaApprovalsCreateTgaApprovalErrors];

export type tgaApprovalsCreateTgaApprovalResponses = {
    /**
     * Successful Response
     */
    201: TgaApprovalRead;
};

export type tgaApprovalsCreateTgaApprovalResponse = tgaApprovalsCreateTgaApprovalResponses[keyof tgaApprovalsCreateTgaApprovalResponses];

export type tgaApprovalsMatchTgaApprovalData = {
    body: TgaMatchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tga-approvals/match';
};

export type tgaApprovalsMatchTgaApprovalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tgaApprovalsMatchTgaApprovalError = tgaApprovalsMatchTgaApprovalErrors[keyof tgaApprovalsMatchTgaApprovalErrors];

export type tgaApprovalsMatchTgaApprovalResponses = {
    /**
     * Successful Response
     */
    200: TgaMatchResponse;
};

export type tgaApprovalsMatchTgaApprovalResponse = tgaApprovalsMatchTgaApprovalResponses[keyof tgaApprovalsMatchTgaApprovalResponses];

export type tgaApprovalsReadTgaApprovalData = {
    body?: never;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/api/v1/tga-approvals/{approval_id}';
};

export type tgaApprovalsReadTgaApprovalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tgaApprovalsReadTgaApprovalError = tgaApprovalsReadTgaApprovalErrors[keyof tgaApprovalsReadTgaApprovalErrors];

export type tgaApprovalsReadTgaApprovalResponses = {
    /**
     * Successful Response
     */
    200: TgaApprovalDetail;
};

export type tgaApprovalsReadTgaApprovalResponse = tgaApprovalsReadTgaApprovalResponses[keyof tgaApprovalsReadTgaApprovalResponses];

export type tgaApprovalsVerifyTgaApprovalData = {
    body: TgaApprovalVerify;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/api/v1/tga-approvals/{approval_id}/verify';
};

export type tgaApprovalsVerifyTgaApprovalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tgaApprovalsVerifyTgaApprovalError = tgaApprovalsVerifyTgaApprovalErrors[keyof tgaApprovalsVerifyTgaApprovalErrors];

export type tgaApprovalsVerifyTgaApprovalResponses = {
    /**
     * Successful Response
     */
    200: TgaApprovalRead;
};

export type tgaApprovalsVerifyTgaApprovalResponse = tgaApprovalsVerifyTgaApprovalResponses[keyof tgaApprovalsVerifyTgaApprovalResponses];

export type tgaApprovalsRevokeTgaApprovalData = {
    body: TgaApprovalRevoke;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/api/v1/tga-approvals/{approval_id}/revoke';
};

export type tgaApprovalsRevokeTgaApprovalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tgaApprovalsRevokeTgaApprovalError = tgaApprovalsRevokeTgaApprovalErrors[keyof tgaApprovalsRevokeTgaApprovalErrors];

export type tgaApprovalsRevokeTgaApprovalResponses = {
    /**
     * Successful Response
     */
    200: TgaApprovalRead;
};

export type tgaApprovalsRevokeTgaApprovalResponse = tgaApprovalsRevokeTgaApprovalResponses[keyof tgaApprovalsRevokeTgaApprovalResponses];

export type tgaApprovalsSupersedeTgaApprovalData = {
    body: TgaApprovalSupersede;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/api/v1/tga-approvals/{approval_id}/supersede';
};

export type tgaApprovalsSupersedeTgaApprovalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tgaApprovalsSupersedeTgaApprovalError = tgaApprovalsSupersedeTgaApprovalErrors[keyof tgaApprovalsSupersedeTgaApprovalErrors];

export type tgaApprovalsSupersedeTgaApprovalResponses = {
    /**
     * Successful Response
     */
    201: TgaApprovalRead;
};

export type tgaApprovalsSupersedeTgaApprovalResponse = tgaApprovalsSupersedeTgaApprovalResponses[keyof tgaApprovalsSupersedeTgaApprovalResponses];

export type tgaApprovalsListPatientTgaApprovalsData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/patients/{patient_id}/tga-approvals';
};

export type tgaApprovalsListPatientTgaApprovalsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tgaApprovalsListPatientTgaApprovalsError = tgaApprovalsListPatientTgaApprovalsErrors[keyof tgaApprovalsListPatientTgaApprovalsErrors];

export type tgaApprovalsListPatientTgaApprovalsResponses = {
    /**
     * Successful Response
     */
    200: TgaApprovalsPublic;
};

export type tgaApprovalsListPatientTgaApprovalsResponse = tgaApprovalsListPatientTgaApprovalsResponses[keyof tgaApprovalsListPatientTgaApprovalsResponses];

export type appointmentsListPractitionersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/practitioners';
};

export type appointmentsListPractitionersResponses = {
    /**
     * Response Appointments-List Practitioners
     *
     * Successful Response
     */
    200: Array<PractitionerRead>;
};

export type appointmentsListPractitionersResponse = appointmentsListPractitionersResponses[keyof appointmentsListPractitionersResponses];

export type appointmentsListAppointmentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * From
         */
        from: string;
        /**
         * To
         */
        to: string;
        /**
         * Practitioner Id
         */
        practitioner_id?: string | null;
    };
    url: '/api/v1/appointments';
};

export type appointmentsListAppointmentsErrors = {
    /**
     * Absent, or another organisation's
     */
    404: unknown;
    /**
     * Refused by the booking rules (overlap, slot taken, illegal transition)
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appointmentsListAppointmentsError = appointmentsListAppointmentsErrors[keyof appointmentsListAppointmentsErrors];

export type appointmentsListAppointmentsResponses = {
    /**
     * Response Appointments-List Appointments
     *
     * Successful Response
     */
    200: Array<AppointmentRead>;
};

export type appointmentsListAppointmentsResponse = appointmentsListAppointmentsResponses[keyof appointmentsListAppointmentsResponses];

export type appointmentsCreateAppointmentData = {
    body: AppointmentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/appointments';
};

export type appointmentsCreateAppointmentErrors = {
    /**
     * Absent, or another organisation's
     */
    404: unknown;
    /**
     * Refused by the booking rules (overlap, slot taken, illegal transition)
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appointmentsCreateAppointmentError = appointmentsCreateAppointmentErrors[keyof appointmentsCreateAppointmentErrors];

export type appointmentsCreateAppointmentResponses = {
    /**
     * Successful Response
     */
    201: AppointmentRead;
};

export type appointmentsCreateAppointmentResponse = appointmentsCreateAppointmentResponses[keyof appointmentsCreateAppointmentResponses];

export type appointmentsChangeAppointmentStatusData = {
    body: AppointmentStatusUpdate;
    path: {
        /**
         * Appointment Id
         */
        appointment_id: string;
    };
    query?: never;
    url: '/api/v1/appointments/{appointment_id}/status';
};

export type appointmentsChangeAppointmentStatusErrors = {
    /**
     * Absent, or another organisation's
     */
    404: unknown;
    /**
     * Refused by the booking rules (overlap, slot taken, illegal transition)
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appointmentsChangeAppointmentStatusError = appointmentsChangeAppointmentStatusErrors[keyof appointmentsChangeAppointmentStatusErrors];

export type appointmentsChangeAppointmentStatusResponses = {
    /**
     * Successful Response
     */
    200: AppointmentRead;
};

export type appointmentsChangeAppointmentStatusResponse = appointmentsChangeAppointmentStatusResponses[keyof appointmentsChangeAppointmentStatusResponses];

export type appointmentsListPatientAppointmentsData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}/appointments';
};

export type appointmentsListPatientAppointmentsErrors = {
    /**
     * Absent, or another organisation's
     */
    404: unknown;
    /**
     * Refused by the booking rules (overlap, slot taken, illegal transition)
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type appointmentsListPatientAppointmentsError = appointmentsListPatientAppointmentsErrors[keyof appointmentsListPatientAppointmentsErrors];

export type appointmentsListPatientAppointmentsResponses = {
    /**
     * Response Appointments-List Patient Appointments
     *
     * Successful Response
     */
    200: Array<AppointmentRead>;
};

export type appointmentsListPatientAppointmentsResponse = appointmentsListPatientAppointmentsResponses[keyof appointmentsListPatientAppointmentsResponses];

export type publicBookingListPublicSlotsData = {
    body?: never;
    path: {
        /**
         * Clinic Slug
         */
        clinic_slug: string;
    };
    query: {
        /**
         * Type
         */
        type: 'NURSE_TRIAGE' | 'INITIAL_CONSULT' | 'FOLLOW_UP';
    };
    url: '/api/v1/public/{clinic_slug}/slots';
};

export type publicBookingListPublicSlotsErrors = {
    /**
     * No such clinic, or not taking bookings
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type publicBookingListPublicSlotsError = publicBookingListPublicSlotsErrors[keyof publicBookingListPublicSlotsErrors];

export type publicBookingListPublicSlotsResponses = {
    /**
     * Response Public-Booking-List Public Slots
     *
     * Successful Response
     */
    200: Array<PublicSlot>;
};

export type publicBookingListPublicSlotsResponse = publicBookingListPublicSlotsResponses[keyof publicBookingListPublicSlotsResponses];

export type publicBookingCreatePublicBookingData = {
    body: PublicBookingRequest;
    path: {
        /**
         * Clinic Slug
         */
        clinic_slug: string;
    };
    query?: never;
    url: '/api/v1/public/{clinic_slug}/bookings';
};

export type publicBookingCreatePublicBookingErrors = {
    /**
     * No such clinic, or not taking bookings
     */
    404: unknown;
    /**
     * `SLOT_TAKEN`: somebody booked that time first
     */
    409: unknown;
    /**
     * Not `application/json`
     */
    415: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type publicBookingCreatePublicBookingError = publicBookingCreatePublicBookingErrors[keyof publicBookingCreatePublicBookingErrors];

export type publicBookingCreatePublicBookingResponses = {
    /**
     * Successful Response
     */
    201: PublicBookingCreated;
};

export type publicBookingCreatePublicBookingResponse = publicBookingCreatePublicBookingResponses[keyof publicBookingCreatePublicBookingResponses];

export type authStepUpData = {
    body: StepUpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/step-up';
};

export type authStepUpErrors = {
    /**
     * `STEP_UP_FAILED`: the password did not verify. Audited; nothing issued.
     */
    403: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type authStepUpError = authStepUpErrors[keyof authStepUpErrors];

export type authStepUpResponses = {
    /**
     * Successful Response
     */
    201: StepUpGrantRead;
};

export type authStepUpResponse = authStepUpResponses[keyof authStepUpResponses];

export type prescriptionsListPrescriptionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * State
         */
        state?: Array<'DRAFT' | 'SIGNED' | 'BLOCKED' | 'QUEUED' | 'DISPATCHED' | 'FAILED' | 'REQUIRES_RECONCILIATION' | 'CANCELLED' | 'REVERSED'> | null;
        /**
         * Prescriber Id
         */
        prescriber_id?: string | null;
        /**
         * Patient Id
         */
        patient_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/prescriptions';
};

export type prescriptionsListPrescriptionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type prescriptionsListPrescriptionsError = prescriptionsListPrescriptionsErrors[keyof prescriptionsListPrescriptionsErrors];

export type prescriptionsListPrescriptionsResponses = {
    /**
     * Successful Response
     */
    200: PrescriptionsPublic;
};

export type prescriptionsListPrescriptionsResponse = prescriptionsListPrescriptionsResponses[keyof prescriptionsListPrescriptionsResponses];

export type prescriptionsStagePrescriptionData = {
    body: PrescriptionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/prescriptions';
};

export type prescriptionsStagePrescriptionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type prescriptionsStagePrescriptionError = prescriptionsStagePrescriptionErrors[keyof prescriptionsStagePrescriptionErrors];

export type prescriptionsStagePrescriptionResponses = {
    /**
     * Successful Response
     */
    201: PrescriptionRead;
};

export type prescriptionsStagePrescriptionResponse = prescriptionsStagePrescriptionResponses[keyof prescriptionsStagePrescriptionResponses];

export type prescriptionsListPrescribersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/prescriptions/prescribers';
};

export type prescriptionsListPrescribersResponses = {
    /**
     * Successful Response
     */
    200: PrescribersPublic;
};

export type prescriptionsListPrescribersResponse = prescriptionsListPrescribersResponses[keyof prescriptionsListPrescribersResponses];

export type prescriptionsSignPrescriptionData = {
    body: PrescriptionSign;
    path: {
        /**
         * Prescription Id
         */
        prescription_id: string;
    };
    query?: never;
    url: '/api/v1/prescriptions/{prescription_id}/sign';
};

export type prescriptionsSignPrescriptionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type prescriptionsSignPrescriptionError = prescriptionsSignPrescriptionErrors[keyof prescriptionsSignPrescriptionErrors];

export type prescriptionsSignPrescriptionResponses = {
    /**
     * Successful Response
     */
    200: PrescriptionRead;
};

export type prescriptionsSignPrescriptionResponse = prescriptionsSignPrescriptionResponses[keyof prescriptionsSignPrescriptionResponses];

export type prescriptionsDispatchPrescriptionData = {
    body: PrescriptionDispatch;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
    };
    path: {
        /**
         * Prescription Id
         */
        prescription_id: string;
    };
    query?: never;
    url: '/api/v1/prescriptions/{prescription_id}/dispatch';
};

export type prescriptionsDispatchPrescriptionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type prescriptionsDispatchPrescriptionError = prescriptionsDispatchPrescriptionErrors[keyof prescriptionsDispatchPrescriptionErrors];

export type prescriptionsDispatchPrescriptionResponses = {
    /**
     * A replay of an earlier `Idempotency-Key`: nothing changed.
     */
    200: PrescriptionRead;
    /**
     * Successful Response
     */
    202: PrescriptionRead;
};

export type prescriptionsDispatchPrescriptionResponse = prescriptionsDispatchPrescriptionResponses[keyof prescriptionsDispatchPrescriptionResponses];

export type dashboardReadTodayData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/today';
};

export type dashboardReadTodayResponses = {
    /**
     * Successful Response
     */
    200: TodaySummary;
};

export type dashboardReadTodayResponse = dashboardReadTodayResponses[keyof dashboardReadTodayResponses];
