// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AuditEventRead
 *
 * One audit event as the API returns it — the design's envelope, and nothing else.
 *
 * `tenant_id` is not declared: the caller already knows its own tenant, and the row was read under
 * it. `prev_hash` and `hash` are exposed because verifying the trail is the point of reading it.
 */
export type AuditEventRead = {
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Actor Id
     */
    actor_id?: string | null;
    /**
     * Actor Role
     */
    actor_role?: string | null;
    /**
     * Action
     */
    action: string;
    /**
     * Resource Type
     */
    resource_type: string;
    /**
     * Resource Id
     */
    resource_id?: string | null;
    /**
     * Result
     */
    result: string;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Source Ip
     */
    source_ip?: string | null;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Correlation Id
     */
    correlation_id?: string | null;
    /**
     * Prev Hash
     */
    prev_hash: string;
    /**
     * Hash
     */
    hash: string;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    } | null;
};

/**
 * AuditEventsPublic
 *
 * A keyset page of audit events.
 *
 * `next_cursor` is opaque and `None` on the last page. `count` is the number of rows in this page,
 * not the tenant's total: the total is not disclosed and is not knowable without a scan, which R12
 * refuses.
 */
export type AuditEventsPublic = {
    /**
     * Data
     */
    data: Array<AuditEventRead>;
    /**
     * Count
     */
    count: number;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ClinicalRecordAppend
 *
 * The body of `PATCH /api/v1/clinical-records/{id}` and of `POST .../amendments`.
 *
 * Both routes append: the design says they are *"the same code path"*, so they share this schema.
 * A version is a complete document, not a patch to be merged, so the narrative is required in
 * full — an append that omitted it would have to copy the previous narrative forward, which would
 * silently attribute old text to a new author and time.
 *
 * `amendment_reason` is the design's API field for the `reason` column. Requirement R7 makes it
 * mandatory whenever the new version number is above 1; that check needs the record's current
 * version, so it runs in the service with the record loaded, and answers
 * `422 AMENDMENT_REASON_REQUIRED`.
 */
export type ClinicalRecordAppend = {
    /**
     * Body
     */
    body?: string | null;
    /**
     * Body Format
     */
    body_format?: string | null;
    soap?: SoapNote | null;
    /**
     * Amendment Reason
     */
    amendment_reason?: string | null;
};

/**
 * ClinicalRecordCreate
 *
 * The body of `POST /api/v1/clinical-records` (R1, R2).
 *
 * There is no `tenant_id`, `author_id`, `signed_at`, `version` or `current_version` field and
 * there never will be: `extra="forbid"` turns one into a `422` (R2).
 */
export type ClinicalRecordCreate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Record Type
     */
    record_type?: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Body Format
     */
    body_format?: string | null;
    soap?: SoapNote | null;
};

/**
 * ClinicalRecordDetail
 *
 * A record plus every version, ascending (R9). The shape `GET .../{id}` returns.
 */
export type ClinicalRecordDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Record Type
     */
    record_type: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Current Version
     */
    current_version: number;
    /**
     * Signed At
     */
    signed_at?: string | null;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Versions
     */
    versions: Array<ClinicalRecordVersionRead>;
};

/**
 * ClinicalRecordSummary
 *
 * One timeline entry: the record's metadata and its current version's narrative.
 */
export type ClinicalRecordSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Record Type
     */
    record_type: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Current Version
     */
    current_version: number;
    /**
     * Signed At
     */
    signed_at?: string | null;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    latest_version: ClinicalRecordVersionRead;
};

/**
 * ClinicalRecordVersionRead
 *
 * One version as the API returns it.
 *
 * No `tenant_id` is declared: the caller already knows its own tenant, and nothing that is not
 * needed is exposed. `body` is `HIGHLY_SENSITIVE` and this model is the **only** place it is
 * serialised — never into a log line, an error envelope or an audit payload (INV-5, R15).
 */
export type ClinicalRecordVersionRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Clinical Record Id
     */
    clinical_record_id: string;
    /**
     * Version
     */
    version: number;
    /**
     * Body
     */
    body: string;
    /**
     * Body Format
     */
    body_format: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Signed At
     */
    signed_at?: string | null;
    /**
     * Supersedes Version
     */
    supersedes_version?: number | null;
    /**
     * Amendment Reason
     */
    amendment_reason?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ClinicalRecordsPublic
 *
 * A keyset page of the patient timeline plus the cursor for the next page.
 */
export type ClinicalRecordsPublic = {
    /**
     * Data
     */
    data: Array<ClinicalRecordSummary>;
    /**
     * Count
     */
    count: number;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PatientCreate
 *
 * The body of `POST /api/v1/patients`.
 *
 * There is no `tenant_id` field and there never will be: `extra="forbid"` turns one into
 * a `422` (INV-1). Identifier columns are absent for the same reason — their key custody
 * is an open item (`04-database-erd.md` open item 5), so no value is accepted yet.
 */
export type PatientCreate = {
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Preferred Name
     */
    preferred_name?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth: string;
    /**
     * Sex At Birth
     */
    sex_at_birth?: string | null;
    /**
     * Gender Identity
     */
    gender_identity?: string | null;
    /**
     * Address Line
     */
    address_line?: string | null;
    /**
     * Suburb
     */
    suburb?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postcode
     */
    postcode?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Deceased At
     */
    deceased_at?: string | null;
};

/**
 * PatientRead
 *
 * A patient as the API returns it.
 *
 * `from_attributes` lets the service hand over a declared model rather than a raw ORM
 * entity. No identifier column and no `tenant_id` is declared: the caller already knows
 * its own tenant, and nothing that is not needed is exposed.
 */
export type PatientRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Given Name
     */
    given_name: string;
    /**
     * Family Name
     */
    family_name: string;
    /**
     * Preferred Name
     */
    preferred_name?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth: string;
    /**
     * Sex At Birth
     */
    sex_at_birth?: string | null;
    /**
     * Gender Identity
     */
    gender_identity?: string | null;
    /**
     * Address Line
     */
    address_line?: string | null;
    /**
     * Suburb
     */
    suburb?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postcode
     */
    postcode?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Deceased At
     */
    deceased_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PatientUpdate
 *
 * The body of `PATCH /api/v1/patients/{patient_id}`.
 *
 * Every field is optional and applied with `exclude_unset`, so an omitted field is left
 * alone and an explicit `null` clears a nullable one. A `null` for a NOT NULL column is
 * rejected here rather than at the database.
 */
export type PatientUpdate = {
    /**
     * Given Name
     */
    given_name?: string | null;
    /**
     * Family Name
     */
    family_name?: string | null;
    /**
     * Preferred Name
     */
    preferred_name?: string | null;
    /**
     * Date Of Birth
     */
    date_of_birth?: string | null;
    /**
     * Sex At Birth
     */
    sex_at_birth?: string | null;
    /**
     * Gender Identity
     */
    gender_identity?: string | null;
    /**
     * Address Line
     */
    address_line?: string | null;
    /**
     * Suburb
     */
    suburb?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Postcode
     */
    postcode?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Deceased At
     */
    deceased_at?: string | null;
};

/**
 * PatientsPublic
 *
 * A bounded page of patients plus the caller's total, following `UsersPublic`.
 */
export type PatientsPublic = {
    /**
     * Data
     */
    data: Array<PatientRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * PermissionRead
 *
 * One entry of the global permission catalogue.
 *
 * `permissions.id` is not exposed: `code` is the catalogue's stable identity and the join key is
 * internal. `permissions` is global read-only reference data (R7).
 */
export type PermissionRead = {
    /**
     * Code
     */
    code: string;
    /**
     * Description
     */
    description: string;
};

/**
 * PermissionsPublic
 *
 * The permission catalogue, or a computed subset of it, plus its size.
 */
export type PermissionsPublic = {
    /**
     * Data
     */
    data: Array<PermissionRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * RoleAssignmentCreate
 *
 * The body of `POST /api/v1/users/{user_id}/roles`.
 *
 * Only `role_id` is accepted. A `tenant_id` (INV-1), a `granted_by` or a `user_id` is an unknown
 * field and is rejected `422` before any query runs — the design's step 5 names exactly those three.
 */
export type RoleAssignmentCreate = {
    /**
     * Role Id
     */
    role_id: string;
};

/**
 * RoleRead
 *
 * A tenant-scoped role and the permission bundle it resolves to.
 */
export type RoleRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is System
     */
    is_system: boolean;
    /**
     * Permissions
     */
    permissions: Array<PermissionRead>;
};

/**
 * RolesPublic
 *
 * The organisation's roles, ordered by code, plus their count.
 */
export type RolesPublic = {
    /**
     * Data
     */
    data: Array<RoleRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * SoapNote
 *
 * The `subjective` / `objective` / `assessment` / `plan` authoring surface.
 *
 * This is a **serialisation** of the single narrative column, never a storage shape: the service
 * renders it into `clinical_record_versions.body` and no SOAP column exists anywhere (R3).
 */
export type SoapNote = {
    /**
     * Subjective
     */
    subjective?: string | null;
    /**
     * Objective
     */
    objective?: string | null;
    /**
     * Assessment
     */
    assessment?: string | null;
    /**
     * Plan
     */
    plan?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPermissionsRead
 *
 * The effective permission set of one account, computed server-side from its roles.
 *
 * The design names this "effective set, computed server-side": nothing here comes from the request,
 * and the set is the union of the account's role bundles (R1).
 */
export type UserPermissionsRead = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Permissions
     */
    permissions: Array<PermissionRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Tenant Id
     */
    tenant_id?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Clinic Name
     */
    clinic_name?: string | null;
};

/**
 * UserRoleRead
 *
 * One role an account holds inside the caller's tenant.
 *
 * `granted_at` is returned because an access review needs the age of the grant (US-2); the granter's
 * identifier is not.
 */
export type UserRoleRead = {
    /**
     * Role Id
     */
    role_id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is System
     */
    is_system: boolean;
    /**
     * Granted At
     */
    granted_at: string;
};

/**
 * UserRolesPublic
 *
 * The roles one account holds, plus their count.
 */
export type UserRolesPublic = {
    /**
     * Data
     */
    data: Array<UserRoleRead>;
    /**
     * Count
     */
    count: number;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type healthReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready/';
};

export type healthReadinessErrors = {
    /**
     * The process cannot reach its database.
     */
    503: boolean;
};

export type healthReadinessError = healthReadinessErrors[keyof healthReadinessErrors];

export type healthReadinessResponses = {
    /**
     * The process can serve requests.
     */
    200: boolean;
};

export type healthReadinessResponse = healthReadinessResponses[keyof healthReadinessResponses];

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type patientsListPatientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/patients';
};

export type patientsListPatientsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsListPatientsError = patientsListPatientsErrors[keyof patientsListPatientsErrors];

export type patientsListPatientsResponses = {
    /**
     * Successful Response
     */
    200: PatientsPublic;
};

export type patientsListPatientsResponse = patientsListPatientsResponses[keyof patientsListPatientsResponses];

export type patientsCreatePatientData = {
    body: PatientCreate;
    path?: never;
    query?: never;
    url: '/api/v1/patients';
};

export type patientsCreatePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsCreatePatientError = patientsCreatePatientErrors[keyof patientsCreatePatientErrors];

export type patientsCreatePatientResponses = {
    /**
     * Successful Response
     */
    201: PatientRead;
};

export type patientsCreatePatientResponse = patientsCreatePatientResponses[keyof patientsCreatePatientResponses];

export type patientsReadPatientData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}';
};

export type patientsReadPatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsReadPatientError = patientsReadPatientErrors[keyof patientsReadPatientErrors];

export type patientsReadPatientResponses = {
    /**
     * Successful Response
     */
    200: PatientRead;
};

export type patientsReadPatientResponse = patientsReadPatientResponses[keyof patientsReadPatientResponses];

export type patientsUpdatePatientData = {
    body: PatientUpdate;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/patients/{patient_id}';
};

export type patientsUpdatePatientErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type patientsUpdatePatientError = patientsUpdatePatientErrors[keyof patientsUpdatePatientErrors];

export type patientsUpdatePatientResponses = {
    /**
     * Successful Response
     */
    200: PatientRead;
};

export type patientsUpdatePatientResponse = patientsUpdatePatientResponses[keyof patientsUpdatePatientResponses];

export type rolesListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/roles';
};

export type rolesListRolesResponses = {
    /**
     * Successful Response
     */
    200: RolesPublic;
};

export type rolesListRolesResponse = rolesListRolesResponses[keyof rolesListRolesResponses];

export type permissionsListPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/permissions';
};

export type permissionsListPermissionsResponses = {
    /**
     * Successful Response
     */
    200: PermissionsPublic;
};

export type permissionsListPermissionsResponse = permissionsListPermissionsResponses[keyof permissionsListPermissionsResponses];

export type usersReadUserRolesData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/roles';
};

export type usersReadUserRolesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserRolesError = usersReadUserRolesErrors[keyof usersReadUserRolesErrors];

export type usersReadUserRolesResponses = {
    /**
     * Successful Response
     */
    200: UserRolesPublic;
};

export type usersReadUserRolesResponse = usersReadUserRolesResponses[keyof usersReadUserRolesResponses];

export type usersAssignRoleData = {
    body: RoleAssignmentCreate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/roles';
};

export type usersAssignRoleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersAssignRoleError = usersAssignRoleErrors[keyof usersAssignRoleErrors];

export type usersAssignRoleResponses = {
    /**
     * The account already held the role; nothing was written
     */
    200: RoleRead;
    /**
     * Successful Response
     */
    201: RoleRead;
};

export type usersAssignRoleResponse = usersAssignRoleResponses[keyof usersAssignRoleResponses];

export type usersReadUserPermissionsData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/permissions';
};

export type usersReadUserPermissionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserPermissionsError = usersReadUserPermissionsErrors[keyof usersReadUserPermissionsErrors];

export type usersReadUserPermissionsResponses = {
    /**
     * Successful Response
     */
    200: UserPermissionsRead;
};

export type usersReadUserPermissionsResponse = usersReadUserPermissionsResponses[keyof usersReadUserPermissionsResponses];

export type usersRevokeRoleData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/roles/{role_id}';
};

export type usersRevokeRoleErrors = {
    /**
     * Refused: this is the organisation's last role granting `users:manage` (R8). Assign another administrator first.
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRevokeRoleError = usersRevokeRoleErrors[keyof usersRevokeRoleErrors];

export type usersRevokeRoleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersRevokeRoleResponse = usersRevokeRoleResponses[keyof usersRevokeRoleResponses];

export type auditListAuditEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Action
         */
        action?: string | null;
        /**
         * Actor Id
         */
        actor_id?: string | null;
        /**
         * Resource Type
         */
        resource_type?: string | null;
        /**
         * Resource Id
         */
        resource_id?: string | null;
        /**
         * Result
         */
        result?: string | null;
        /**
         * From
         */
        from?: string | null;
        /**
         * To
         */
        to?: string | null;
    };
    url: '/api/v1/audit/events';
};

export type auditListAuditEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type auditListAuditEventsError = auditListAuditEventsErrors[keyof auditListAuditEventsErrors];

export type auditListAuditEventsResponses = {
    /**
     * Successful Response
     */
    200: AuditEventsPublic;
};

export type auditListAuditEventsResponse = auditListAuditEventsResponses[keyof auditListAuditEventsResponses];

export type auditReadAuditEventData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/api/v1/audit/events/{event_id}';
};

export type auditReadAuditEventErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type auditReadAuditEventError = auditReadAuditEventErrors[keyof auditReadAuditEventErrors];

export type auditReadAuditEventResponses = {
    /**
     * Successful Response
     */
    200: AuditEventRead;
};

export type auditReadAuditEventResponse = auditReadAuditEventResponses[keyof auditReadAuditEventResponses];

export type clinicalRecordsCreateClinicalRecordData = {
    body: ClinicalRecordCreate;
    path?: never;
    query?: never;
    url: '/api/v1/clinical-records';
};

export type clinicalRecordsCreateClinicalRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsCreateClinicalRecordError = clinicalRecordsCreateClinicalRecordErrors[keyof clinicalRecordsCreateClinicalRecordErrors];

export type clinicalRecordsCreateClinicalRecordResponses = {
    /**
     * Successful Response
     */
    201: ClinicalRecordDetail;
};

export type clinicalRecordsCreateClinicalRecordResponse = clinicalRecordsCreateClinicalRecordResponses[keyof clinicalRecordsCreateClinicalRecordResponses];

export type clinicalRecordsReadClinicalRecordData = {
    body?: never;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}';
};

export type clinicalRecordsReadClinicalRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsReadClinicalRecordError = clinicalRecordsReadClinicalRecordErrors[keyof clinicalRecordsReadClinicalRecordErrors];

export type clinicalRecordsReadClinicalRecordResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordDetail;
};

export type clinicalRecordsReadClinicalRecordResponse = clinicalRecordsReadClinicalRecordResponses[keyof clinicalRecordsReadClinicalRecordResponses];

export type clinicalRecordsAppendClinicalRecordVersionData = {
    body: ClinicalRecordAppend;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}';
};

export type clinicalRecordsAppendClinicalRecordVersionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsAppendClinicalRecordVersionError = clinicalRecordsAppendClinicalRecordVersionErrors[keyof clinicalRecordsAppendClinicalRecordVersionErrors];

export type clinicalRecordsAppendClinicalRecordVersionResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordDetail;
};

export type clinicalRecordsAppendClinicalRecordVersionResponse = clinicalRecordsAppendClinicalRecordVersionResponses[keyof clinicalRecordsAppendClinicalRecordVersionResponses];

export type clinicalRecordsReadClinicalRecordVersionData = {
    body?: never;
    path: {
        /**
         * Record Id
         */
        record_id: string;
        /**
         * Version
         */
        version: number;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}/versions/{version}';
};

export type clinicalRecordsReadClinicalRecordVersionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsReadClinicalRecordVersionError = clinicalRecordsReadClinicalRecordVersionErrors[keyof clinicalRecordsReadClinicalRecordVersionErrors];

export type clinicalRecordsReadClinicalRecordVersionResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordVersionRead;
};

export type clinicalRecordsReadClinicalRecordVersionResponse = clinicalRecordsReadClinicalRecordVersionResponses[keyof clinicalRecordsReadClinicalRecordVersionResponses];

export type clinicalRecordsListPatientClinicalRecordsData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
    };
    url: '/api/v1/patients/{patient_id}/clinical-records';
};

export type clinicalRecordsListPatientClinicalRecordsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsListPatientClinicalRecordsError = clinicalRecordsListPatientClinicalRecordsErrors[keyof clinicalRecordsListPatientClinicalRecordsErrors];

export type clinicalRecordsListPatientClinicalRecordsResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordsPublic;
};

export type clinicalRecordsListPatientClinicalRecordsResponse = clinicalRecordsListPatientClinicalRecordsResponses[keyof clinicalRecordsListPatientClinicalRecordsResponses];

export type clinicalRecordsAmendClinicalRecordData = {
    body: ClinicalRecordAppend;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}/amendments';
};

export type clinicalRecordsAmendClinicalRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsAmendClinicalRecordError = clinicalRecordsAmendClinicalRecordErrors[keyof clinicalRecordsAmendClinicalRecordErrors];

export type clinicalRecordsAmendClinicalRecordResponses = {
    /**
     * Successful Response
     */
    201: ClinicalRecordDetail;
};

export type clinicalRecordsAmendClinicalRecordResponse = clinicalRecordsAmendClinicalRecordResponses[keyof clinicalRecordsAmendClinicalRecordResponses];

export type clinicalRecordsSignClinicalRecordData = {
    body?: never;
    path: {
        /**
         * Record Id
         */
        record_id: string;
    };
    query?: never;
    url: '/api/v1/clinical-records/{record_id}/sign';
};

export type clinicalRecordsSignClinicalRecordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type clinicalRecordsSignClinicalRecordError = clinicalRecordsSignClinicalRecordErrors[keyof clinicalRecordsSignClinicalRecordErrors];

export type clinicalRecordsSignClinicalRecordResponses = {
    /**
     * Successful Response
     */
    200: ClinicalRecordDetail;
};

export type clinicalRecordsSignClinicalRecordResponse = clinicalRecordsSignClinicalRecordResponses[keyof clinicalRecordsSignClinicalRecordResponses];
