"""create tenants

Revision ID: 706856e36a80
Revises: fe56fa70289e
Create Date: 2026-10-05 12:02:32.098388

The `tenants` table: docs/features/01-tenancy-and-clinics/03-design.md,
"Table: tenants (GLOBAL — no RLS)". Global by design, so no row-level security here;
tenant context is proven from the actor's session and the addressed resource.

Grants are deliberately absent. The design grants column-level SELECT to `clinos_app`,
but that role is created by task T1-11, so there is nothing to grant to yet.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '706856e36a80'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('data_region', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('retention_profile', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'CLOSING', 'CLOSED')", name='ck_tenants_status'),
    sa.CheckConstraint('slug = lower(slug)', name='ck_tenants_slug_lowercase'),
    # Pinned: this migration predates the shared naming convention, and
    # fb0ce1f1fff5 renames the constraint from this name.
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
