"""drop the item table

Revision ID: 89d27ee38a6f
Revises: fb0ce1f1fff5
Create Date: 2026-10-05 14:11:45.963547

`item` was the upstream template's example domain. This product has no such
concept, and it shipped a public API surface (`/api/v1/items/*`), a UI section and
a CRUD test suite that a clinical platform should not carry.

The downgrade recreates the table using the current naming convention, so a
downgrade followed by an upgrade leaves the schema as `alembic check` expects.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89d27ee38a6f'
down_revision = 'fb0ce1f1fff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_item_owner_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    # ### end Alembic commands ###
